[package]
name = "cornetroll"
version = "0.4.0"
authors = ["Mark Nokalt <marknokalt@live.com>"]
edition = "2021"

[dependencies]
clap = "4.5"
mpris = "2.0"
signal-hook = "0.3"
unix-named-pipe = "0.2"
crossterm = "0.27"
